# version: "3.8"
# services:
#   mongo:
#     image: mongo:7.0
#     container_name: "nodegmp-nosql"
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: admin
#       MONGO_INITDB_ROOT_PASSWORD: admin123
#     ports:
#       - 27017:27017
#     volumes:
#       - mongo-data:/data/db
# volumes:
#   mongo-data:
#     driver: local

version: "3"
services:
  mongo:
    image: "mongo"
    container_name: "nodegmp-nosql"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=nodegmp
    ports:
      - "27017:27017"
