version: "3"
services:
  mongo:
    image: "mongo"
    container_name: "nodegmp-nosql"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=nodegmp
    ports:
      - "27017:27017"
  app:
    container_name: my_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    restart: always
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    depends_on:
      - mongo
